services:
  - docker

sudo: required
env:
  - GO111MODULE=on IMAGE=jrei/systemd-ubuntu:16.04
  - GO111MODULE=on IMAGE=jrei/systemd-ubuntu:18.04
  - GO111MODULE=on IMAGE=jrei/systemd-centos
  - GO111MODULE=on IMAGE=jrei/systemd-fedora
  - GO111MODULE=on IMAGE=jrei/systemd-debian


language: go
go:
  - 1.11.x

before_install:
  - go mod download

script:
  - make all

deploy:
  provider: script
  script: bash scripts/release.sh
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
