language: go

go:
  - 1.11.x

before_install:
  - GO111MODULE=on go get -t -v ./...

script:
  - go test -v ./pkg/... ./cmd/... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)