language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - go test -v ./pkg/... ./cmd/... -race -coverprofile=coverage.txt -covermode=atomic

deploy:
  provider: script
  script: bash scripts/release.sh
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)