services:
  - docker

sudo: required
env:
  - GO111MODULE=on IMAGE=jrei/systemd-ubuntu:16.04


language: go
go:
  - 1.11.x

before_install:
  - go mod download
  - sudo pip install mkdocs mkdocs-material pymdown-extensions Pygments

script:
  - make all

deploy:
  provider: script
  script: bash scripts/release.sh
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
