version: 2
jobs:
  build:
    branches:
      ignore: "gh-pages"
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - setup_remote_docker
      - checkout
      - run: go mod download
      - run: make test integration
  publish-github-release:
      environment:
        GO111MODULE: "on"
      docker:
        - image: circleci/golang:1.11
      working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
      steps:
        - checkout
        - run: go mod download
        - run: ./scripts/release.sh
  docs:
    branches:
      ignore: "gh-pages"
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install mkdocs mkdocs-material pymdown-extensions Pygments
      - run: make docs
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - docs:
          context: Github

