version: 2
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - setup_remote_docker
      - checkout
      - run: go mod download
      - run: make test integration
  docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install mkdocs mkdocs-material pymdown-extensions Pygments
      - run: make docs
workflows:
  version: 2
  build:
    jobs:
      - build
      - docs:
          context: Github

