version: 2
go: &go
  environment:
    GO111MODULE: "on"
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/moshloop/konfigadm
jobs:
  build:
    <<: *go
    steps:
      - setup_remote_docker
      - checkout
      - run: go mod download
      - run: make test integration
  publish-github-release:
      <<: *go
      steps:
        - checkout
        - run: go mod download
        - run: ./scripts/release.sh
  docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install mkdocs mkdocs-material pymdown-extensions Pygments
      - run: make docs
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: "gh-pages"
      - publish-github-release:
          context: Github
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - docs:
          filters:
            branches:
              ignore: "gh-pages"
          context: Github

